version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://splitwise:splitwise@db:5432/splitwise
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=splitwise
      - POSTGRES_PASSWORD=splitwise
      - POSTGRES_DB=splitwise
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 